# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_now_add=True)),
                ('image_hash', models.CharField(db_index=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('absolute_path', models.CharField(max_length=255)),
            ],
        ),
    ]
