# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0002_auto_20160722_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageentity',
            name='image_hash',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
