# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0003_auto_20160722_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageentity',
            name='file_name',
            field=models.CharField(max_length=70),
        ),
    ]
