# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0004_auto_20160722_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageentity',
            name='owner',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
