# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0005_imageentity_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageentity',
            name='absolute_path',
        ),
    ]
