# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0006_remove_imageentity_absolute_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageentity',
            name='file_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='imageentity',
            name='file_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
